spring:
  datasource:
    url: jdbc:postgresql://database-1.cbxzgb3oewch.us-east-1.rds.amazonaws.com/postgres
    username: thepomtrees
    password: pomtrees
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate