spring:
  datasource:
    url: jdbc:postgresql://database-1.cbxzgb3oewch.us-east-1.rds.amazonaws.com:5432/postgres
    username: thepomtrees
    password: pomtrees
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      
server:
  port:
    8085


      